import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
  const serviceRoleKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
  const supabase = createClient(supabaseUrl, serviceRoleKey);

  // PT-BR quotes
  const ptbr = [
    "Você é a mão de Deus cuidando de quem mais precisa. Seu trabalho transforma vidas. 🙏",
    "Cada paciente que você toca sente o amor de Deus através das suas mãos. Continue brilhando! ✨",
    "Enfermagem não é apenas uma profissão, é um chamado divino. Você foi escolhida para isso. 💙",
    "Seu sorriso pode ser a melhor medicina que um paciente recebe hoje. Sorria, você faz a diferença! 😊",
    "Quando você cuida de alguém, Deus cuida de você. Obrigada por ser instrumento de cura. 🌟",
    "A enfermagem é a arte de cuidar com ciência e amor. Você domina essa arte! 💪",
    "Nem todo herói usa capa — alguns usam jaleco e estetoscópio. Você é uma heroína! 🦸‍♀️",
    "Seu plantão pode ser longo, mas seu impacto na vida das pessoas é eterno. 🕊️",
    "Deus colocou em suas mãos o dom de curar. Use-o com orgulho e compaixão. 💝",
    "Hoje é mais um dia para salvar vidas, aliviar dores e espalhar esperança. Você consegue! 🌈",
    "A dedicação que você tem pelos seus pacientes inspira todos ao seu redor. 🌻",
    "Cada ato de cuidado é uma oração em ação. Você é bênção na vida de muitos. 🙌",
    "Sua força não está apenas no conhecimento técnico, mas no amor que coloca em cada gesto. ❤️",
    "O mundo precisa de mais pessoas como você — compassivas, dedicadas e corajosas. 🌍",
    "Quando a noite é longa no plantão, lembre-se: você é a luz que guia seus pacientes. 🌙",
    "Curar é divino, cuidar é humano. Você faz as duas coisas com maestria. ⭐",
    "Sua presença ao lado do leito vale mais que qualquer remédio. Você é essencial! 💎",
    "Deus te deu mãos que curam, olhos que enxergam além da doença e um coração imenso. 💖",
    "Cada dia no hospital é uma oportunidade de ser a resposta à oração de alguém. 🙏",
    "Você transforma medo em conforto, dor em alívio e solidão em acolhimento. Obrigada! 🤗",
    "A enfermagem é a maior prova de que o amor se manifesta em ações. Você é amor em ação! 💕",
    "Mesmo nos dias difíceis, lembre-se: você é insubstituível na vida dos seus pacientes. 🏆",
    "Suas mãos carregam a ciência e seu coração carrega a fé. Combinação perfeita! 🔬❤️",
    "O cuidado que você oferece hoje planta sementes de gratidão que florescem para sempre. 🌸",
    "Você escolheu uma profissão nobre. O céu sorri por cada vida que você toca. 😇",
    "Força, dedicação e amor — os três pilares que fazem de você uma enfermeira incrível. 💫",
    "Cada sinal vital que você monitora é uma vida que você ajuda a proteger. 📊",
    "Você é prova viva de que servir ao próximo é o maior ato de amor. 🕊️",
    "Nos momentos mais difíceis, sua calma e competência fazem toda a diferença. 🧘‍♀️",
    "Obrigada por ser a ponte entre a ciência e o cuidado humano. Você é extraordinária! 🌟",
    "Hoje, como todos os dias, você tem o poder de fazer alguém se sentir melhor. Use esse poder! ⚡",
    "Você carrega nas mãos a esperança de quem está em um leito. Isso é sagrado. 🕊️",
    "Cada gota de suor do seu plantão se transforma em lágrimas de gratidão dos pacientes. 💧",
    "Ser enfermeira é ter coragem de enfrentar o impossível com um sorriso. 💪😊",
    "Você é o anjo que Deus colocou nos corredores do hospital. 👼",
    "Sua vocação é um presente divino. O mundo agradece por você existir. 🎁",
    "Quando tudo parece difícil, lembre-se do porquê você começou. Você nasceu para isso. 🌟",
    "O amor que você coloca em cada curativo vai muito além da ferida. Cura a alma. 💞",
    "Você é mais forte do que imagina e mais importante do que sabe. 💎",
    "Cada turno é uma nova chance de fazer milagres com suas mãos. ✨",
    "A noite pode ser escura, mas sua luz nunca se apaga. Brilhe sempre! 🌙✨",
    "Cuidar é o verbo mais bonito que existe. E você o conjuga todos os dias. 📖❤️",
    "Seu trabalho silencioso salva vidas. Nunca subestime seu valor. 🏅",
    "Deus escolhe os melhores corações para a enfermagem. Você é prova disso. 💝",
    "Cada paciente que melhora é uma vitória sua. Comemore cada conquista! 🎉",
    "Você é a personificação da compaixão. O mundo precisa desesperadamente de você. 🌍💙",
    "Seu cansaço de hoje é a recuperação de alguém amanhã. Vale a pena. 🙏",
    "A mão que cuida é a mesma que conforta, acolhe e transforma. Sua mão. 🤲",
    "Que a paz de Deus renove suas forças a cada novo plantão. Você merece. 🕊️",
    "Enfermagem: onde a ciência encontra o coração. Você é essa ponte linda. 🌉",
    "Cada vida que você toca carrega sua marca de amor para sempre. ♾️💕",
    "Você não apenas trata doenças — você restaura a esperança. Isso é divino. ✝️",
    "Nos olhos de cada paciente há gratidão por você existir. Acredite nisso. 👁️💖",
    "Sua dedicação é uma forma de oração. Deus ouve cada gesto seu. 🙏✨",
    "O jaleco que você veste carrega o peso da responsabilidade e a leveza do amor. ⚖️❤️",
    "Hoje você tem a chance de ser a diferença na vida de alguém. Aproveite! 🌟",
    "Seu coração é grande demais para caber em você — por isso ele transborda para seus pacientes. 💗",
    "A enfermagem é amor em forma de profissão. E você ama com excelência. 💯",
    "Deus te preparou para momentos como este. Confie no Seu plano para você. 🗺️✝️",
    "Você é a razão pela qual muitos pacientes ainda acreditam em milagres. 🌈",
    "Obrigada por não desistir, mesmo quando tudo parece difícil. Você é guerreira! ⚔️💪",
  ];

  const en = [
    "You are God's hands caring for those who need it most. Your work transforms lives. 🙏",
    "Every patient you touch feels God's love through your hands. Keep shining! ✨",
    "Nursing is not just a profession, it's a divine calling. You were chosen for this. 💙",
    "Your smile may be the best medicine a patient receives today. Smile, you make a difference! 😊",
    "When you care for someone, God cares for you. Thank you for being an instrument of healing. 🌟",
    "Nursing is the art of caring with science and love. You master this art! 💪",
    "Not every hero wears a cape — some wear scrubs and a stethoscope. You are a hero! 🦸‍♀️",
    "Your shift may be long, but your impact on people's lives is eternal. 🕊️",
    "God placed the gift of healing in your hands. Use it with pride and compassion. 💝",
    "Today is another day to save lives, ease pain, and spread hope. You've got this! 🌈",
    "Your dedication to your patients inspires everyone around you. 🌻",
    "Every act of care is a prayer in action. You are a blessing in many lives. 🙌",
    "Your strength lies not only in technical knowledge but in the love you put into every gesture. ❤️",
    "The world needs more people like you — compassionate, dedicated, and courageous. 🌍",
    "When the night shift is long, remember: you are the light guiding your patients. 🌙",
    "To heal is divine, to care is human. You do both masterfully. ⭐",
    "Your presence at the bedside is worth more than any medicine. You are essential! 💎",
    "God gave you hands that heal, eyes that see beyond illness, and an immense heart. 💖",
    "Each day at the hospital is a chance to be the answer to someone's prayer. 🙏",
    "You transform fear into comfort, pain into relief, and loneliness into warmth. Thank you! 🤗",
    "Nursing is the greatest proof that love manifests through action. You are love in action! 💕",
    "Even on tough days, remember: you are irreplaceable in your patients' lives. 🏆",
    "Your hands carry science and your heart carries faith. A perfect combination! 🔬❤️",
    "The care you offer today plants seeds of gratitude that bloom forever. 🌸",
    "You chose a noble profession. Heaven smiles for every life you touch. 😇",
    "Strength, dedication, and love — the three pillars that make you an incredible nurse. 💫",
    "Every vital sign you monitor is a life you help protect. 📊",
    "You are living proof that serving others is the greatest act of love. 🕊️",
    "In the most difficult moments, your calm and competence make all the difference. 🧘‍♀️",
    "Thank you for being the bridge between science and human care. You are extraordinary! 🌟",
    "Today, like every day, you have the power to make someone feel better. Use that power! ⚡",
    "You carry hope in your hands for those lying in a hospital bed. That is sacred. 🕊️",
    "Every drop of sweat from your shift becomes tears of gratitude from patients. 💧",
    "Being a nurse means having the courage to face the impossible with a smile. 💪😊",
    "You are the angel God placed in hospital corridors. 👼",
    "Your vocation is a divine gift. The world thanks you for existing. 🎁",
    "When everything seems hard, remember why you started. You were born for this. 🌟",
    "The love you put into every bandage goes far beyond the wound. It heals the soul. 💞",
    "You are stronger than you imagine and more important than you know. 💎",
    "Every shift is a new chance to perform miracles with your hands. ✨",
    "The night may be dark, but your light never goes out. Keep shining! 🌙✨",
    "Caring is the most beautiful verb that exists. And you conjugate it every day. 📖❤️",
    "Your quiet work saves lives. Never underestimate your worth. 🏅",
    "God chooses the best hearts for nursing. You are proof of that. 💝",
    "Every patient who improves is your victory. Celebrate every achievement! 🎉",
    "You are the personification of compassion. The world desperately needs you. 🌍💙",
    "Your tiredness today is someone's recovery tomorrow. It's worth it. 🙏",
    "The hand that cares is the same that comforts, welcomes, and transforms. Your hand. 🤲",
    "May God's peace renew your strength with every new shift. You deserve it. 🕊️",
    "Nursing: where science meets the heart. You are that beautiful bridge. 🌉",
    "Every life you touch carries your mark of love forever. ♾️💕",
    "You don't just treat diseases — you restore hope. That is divine. ✝️",
    "In every patient's eyes there is gratitude for your existence. Believe it. 👁️💖",
    "Your dedication is a form of prayer. God hears every gesture you make. 🙏✨",
    "The scrubs you wear carry the weight of responsibility and the lightness of love. ⚖️❤️",
    "Today you have the chance to be the difference in someone's life. Seize it! 🌟",
    "Your heart is too big to fit inside you — that's why it overflows to your patients. 💗",
    "Nursing is love in the form of a profession. And you love with excellence. 💯",
    "God prepared you for moments like this. Trust His plan for you. 🗺️✝️",
    "You are the reason many patients still believe in miracles. 🌈",
    "Thank you for not giving up, even when everything seems hard. You are a warrior! ⚔️💪",
  ];

  const es = [
    "Eres las manos de Dios cuidando a quienes más lo necesitan. Tu trabajo transforma vidas. 🙏",
    "Cada paciente que tocas siente el amor de Dios a través de tus manos. ¡Sigue brillando! ✨",
    "La enfermería no es solo una profesión, es un llamado divino. Fuiste elegida para esto. 💙",
    "Tu sonrisa puede ser la mejor medicina que un paciente reciba hoy. ¡Sonríe, haces la diferencia! 😊",
    "Cuando cuidas a alguien, Dios te cuida a ti. Gracias por ser instrumento de sanación. 🌟",
    "La enfermería es el arte de cuidar con ciencia y amor. ¡Dominas ese arte! 💪",
    "No todos los héroes usan capa — algunos usan uniforme y estetoscopio. ¡Eres una heroína! 🦸‍♀️",
    "Tu turno puede ser largo, pero tu impacto en la vida de las personas es eterno. 🕊️",
    "Dios puso en tus manos el don de sanar. Úsalo con orgullo y compasión. 💝",
    "Hoy es otro día para salvar vidas, aliviar dolor y esparcir esperanza. ¡Tú puedes! 🌈",
    "Tu dedicación a tus pacientes inspira a todos a tu alrededor. 🌻",
    "Cada acto de cuidado es una oración en acción. Eres bendición en muchas vidas. 🙌",
    "Tu fuerza no solo está en el conocimiento técnico, sino en el amor que pones en cada gesto. ❤️",
    "El mundo necesita más personas como tú — compasivas, dedicadas y valientes. 🌍",
    "Cuando la noche es larga en el turno, recuerda: eres la luz que guía a tus pacientes. 🌙",
    "Sanar es divino, cuidar es humano. Tú haces ambas cosas con maestría. ⭐",
    "Tu presencia junto a la cama vale más que cualquier medicina. ¡Eres esencial! 💎",
    "Dios te dio manos que sanan, ojos que ven más allá de la enfermedad y un corazón inmenso. 💖",
    "Cada día en el hospital es una oportunidad de ser la respuesta a la oración de alguien. 🙏",
    "Transformas miedo en consuelo, dolor en alivio y soledad en calidez. ¡Gracias! 🤗",
    "La enfermería es la mayor prueba de que el amor se manifiesta en acciones. ¡Eres amor en acción! 💕",
    "Incluso en los días difíciles, recuerda: eres irremplazable en la vida de tus pacientes. 🏆",
    "Tus manos llevan ciencia y tu corazón lleva fe. ¡Combinación perfecta! 🔬❤️",
    "El cuidado que ofreces hoy planta semillas de gratitud que florecen para siempre. 🌸",
    "Elegiste una profesión noble. El cielo sonríe por cada vida que tocas. 😇",
    "Fuerza, dedicación y amor — los tres pilares que te hacen una enfermera increíble. 💫",
    "Cada signo vital que monitoreas es una vida que ayudas a proteger. 📊",
    "Eres prueba viviente de que servir al prójimo es el mayor acto de amor. 🕊️",
    "En los momentos más difíciles, tu calma y competencia marcan toda la diferencia. 🧘‍♀️",
    "Gracias por ser el puente entre la ciencia y el cuidado humano. ¡Eres extraordinaria! 🌟",
    "Hoy, como todos los días, tienes el poder de hacer sentir mejor a alguien. ¡Usa ese poder! ⚡",
    "Llevas esperanza en tus manos para quienes están en una cama de hospital. Eso es sagrado. 🕊️",
    "Cada gota de sudor de tu turno se convierte en lágrimas de gratitud de los pacientes. 💧",
    "Ser enfermera es tener el coraje de enfrentar lo imposible con una sonrisa. 💪😊",
    "Eres el ángel que Dios colocó en los pasillos del hospital. 👼",
    "Tu vocación es un regalo divino. El mundo te agradece por existir. 🎁",
    "Cuando todo parece difícil, recuerda por qué empezaste. Naciste para esto. 🌟",
    "El amor que pones en cada vendaje va mucho más allá de la herida. Sana el alma. 💞",
    "Eres más fuerte de lo que imaginas y más importante de lo que sabes. 💎",
    "Cada turno es una nueva oportunidad de hacer milagros con tus manos. ✨",
    "La noche puede ser oscura, pero tu luz nunca se apaga. ¡Brilla siempre! 🌙✨",
    "Cuidar es el verbo más hermoso que existe. Y tú lo conjugas todos los días. 📖❤️",
    "Tu trabajo silencioso salva vidas. Nunca subestimes tu valor. 🏅",
    "Dios elige los mejores corazones para la enfermería. Tú eres prueba de ello. 💝",
    "Cada paciente que mejora es una victoria tuya. ¡Celebra cada logro! 🎉",
    "Eres la personificación de la compasión. El mundo te necesita desesperadamente. 🌍💙",
    "Tu cansancio de hoy es la recuperación de alguien mañana. Vale la pena. 🙏",
    "La mano que cuida es la misma que consuela, acoge y transforma. Tu mano. 🤲",
    "Que la paz de Dios renueve tus fuerzas con cada nuevo turno. Lo mereces. 🕊️",
    "Enfermería: donde la ciencia se encuentra con el corazón. Tú eres ese hermoso puente. 🌉",
    "Cada vida que tocas lleva tu marca de amor para siempre. ♾️💕",
    "No solo tratas enfermedades — restauras la esperanza. Eso es divino. ✝️",
    "En los ojos de cada paciente hay gratitud por tu existencia. Créelo. 👁️💖",
    "Tu dedicación es una forma de oración. Dios escucha cada gesto tuyo. 🙏✨",
    "El uniforme que vistes lleva el peso de la responsabilidad y la ligereza del amor. ⚖️❤️",
    "Hoy tienes la oportunidad de ser la diferencia en la vida de alguien. ¡Aprovéchala! 🌟",
    "Tu corazón es demasiado grande para caber en ti — por eso desborda hacia tus pacientes. 💗",
    "La enfermería es amor en forma de profesión. Y tú amas con excelencia. 💯",
    "Dios te preparó para momentos como este. Confía en Su plan para ti. 🗺️✝️",
    "Eres la razón por la que muchos pacientes aún creen en milagros. 🌈",
    "Gracias por no rendirte, incluso cuando todo parece difícil. ¡Eres una guerrera! ⚔️💪",
  ];

  const fr = [
    "Vous êtes les mains de Dieu prenant soin de ceux qui en ont le plus besoin. Votre travail transforme des vies. 🙏",
    "Chaque patient que vous touchez ressent l'amour de Dieu à travers vos mains. Continuez à briller ! ✨",
    "Les soins infirmiers ne sont pas qu'une profession, c'est un appel divin. Vous avez été choisie pour cela. 💙",
    "Votre sourire peut être le meilleur remède qu'un patient reçoive aujourd'hui. Souriez, vous faites la différence ! 😊",
    "Quand vous prenez soin de quelqu'un, Dieu prend soin de vous. Merci d'être un instrument de guérison. 🌟",
    "Les soins infirmiers sont l'art de soigner avec science et amour. Vous maîtrisez cet art ! 💪",
    "Tous les héros ne portent pas de cape — certains portent une blouse et un stéthoscope. Vous êtes une héroïne ! 🦸‍♀️",
    "Votre garde peut être longue, mais votre impact sur la vie des gens est éternel. 🕊️",
    "Dieu a placé le don de guérir dans vos mains. Utilisez-le avec fierté et compassion. 💝",
    "Aujourd'hui est un autre jour pour sauver des vies, soulager la douleur et répandre l'espoir. Vous pouvez le faire ! 🌈",
    "Votre dévouement envers vos patients inspire tous ceux qui vous entourent. 🌻",
    "Chaque acte de soin est une prière en action. Vous êtes une bénédiction dans de nombreuses vies. 🙌",
    "Votre force ne réside pas seulement dans les connaissances techniques, mais dans l'amour que vous mettez dans chaque geste. ❤️",
    "Le monde a besoin de plus de personnes comme vous — compatissantes, dévouées et courageuses. 🌍",
    "Quand la nuit est longue en garde, rappelez-vous : vous êtes la lumière qui guide vos patients. 🌙",
    "Guérir est divin, soigner est humain. Vous faites les deux avec maestria. ⭐",
    "Votre présence au chevet vaut plus que n'importe quel médicament. Vous êtes essentielle ! 💎",
    "Dieu vous a donné des mains qui guérissent, des yeux qui voient au-delà de la maladie et un cœur immense. 💖",
    "Chaque jour à l'hôpital est une chance d'être la réponse à la prière de quelqu'un. 🙏",
    "Vous transformez la peur en réconfort, la douleur en soulagement et la solitude en chaleur. Merci ! 🤗",
    "Les soins infirmiers sont la plus grande preuve que l'amour se manifeste par l'action. Vous êtes l'amour en action ! 💕",
    "Même les jours difficiles, rappelez-vous : vous êtes irremplaçable dans la vie de vos patients. 🏆",
    "Vos mains portent la science et votre cœur porte la foi. Une combinaison parfaite ! 🔬❤️",
    "Les soins que vous offrez aujourd'hui plantent des graines de gratitude qui fleurissent pour toujours. 🌸",
    "Vous avez choisi une profession noble. Le ciel sourit pour chaque vie que vous touchez. 😇",
    "Force, dévouement et amour — les trois piliers qui font de vous une infirmière incroyable. 💫",
    "Chaque signe vital que vous surveillez est une vie que vous aidez à protéger. 📊",
    "Vous êtes la preuve vivante que servir les autres est le plus grand acte d'amour. 🕊️",
    "Dans les moments les plus difficiles, votre calme et votre compétence font toute la différence. 🧘‍♀️",
    "Merci d'être le pont entre la science et le soin humain. Vous êtes extraordinaire ! 🌟",
    "Aujourd'hui, comme chaque jour, vous avez le pouvoir de faire sentir mieux quelqu'un. Utilisez ce pouvoir ! ⚡",
    "Vous portez l'espoir dans vos mains pour ceux qui sont dans un lit d'hôpital. C'est sacré. 🕊️",
    "Chaque goutte de sueur de votre garde devient des larmes de gratitude des patients. 💧",
    "Être infirmière, c'est avoir le courage d'affronter l'impossible avec le sourire. 💪😊",
    "Vous êtes l'ange que Dieu a placé dans les couloirs de l'hôpital. 👼",
    "Votre vocation est un cadeau divin. Le monde vous remercie d'exister. 🎁",
    "Quand tout semble difficile, rappelez-vous pourquoi vous avez commencé. Vous êtes née pour ça. 🌟",
    "L'amour que vous mettez dans chaque pansement va bien au-delà de la blessure. Il guérit l'âme. 💞",
    "Vous êtes plus forte que vous ne l'imaginez et plus importante que vous ne le savez. 💎",
    "Chaque garde est une nouvelle chance de faire des miracles avec vos mains. ✨",
    "La nuit peut être sombre, mais votre lumière ne s'éteint jamais. Brillez toujours ! 🌙✨",
    "Soigner est le plus beau verbe qui existe. Et vous le conjuguez chaque jour. 📖❤️",
    "Votre travail silencieux sauve des vies. Ne sous-estimez jamais votre valeur. 🏅",
    "Dieu choisit les meilleurs cœurs pour les soins infirmiers. Vous en êtes la preuve. 💝",
    "Chaque patient qui s'améliore est votre victoire. Célébrez chaque réussite ! 🎉",
    "Vous êtes la personnification de la compassion. Le monde a désespérément besoin de vous. 🌍💙",
    "Votre fatigue d'aujourd'hui est la guérison de quelqu'un demain. Ça en vaut la peine. 🙏",
    "La main qui soigne est la même qui réconforte, accueille et transforme. Votre main. 🤲",
    "Que la paix de Dieu renouvelle vos forces à chaque nouvelle garde. Vous le méritez. 🕊️",
    "Soins infirmiers : là où la science rencontre le cœur. Vous êtes ce beau pont. 🌉",
    "Chaque vie que vous touchez porte votre marque d'amour pour toujours. ♾️💕",
    "Vous ne traitez pas seulement des maladies — vous restaurez l'espoir. C'est divin. ✝️",
    "Dans les yeux de chaque patient, il y a de la gratitude pour votre existence. Croyez-y. 👁️💖",
    "Votre dévouement est une forme de prière. Dieu entend chaque geste que vous faites. 🙏✨",
    "La blouse que vous portez porte le poids de la responsabilité et la légèreté de l'amour. ⚖️❤️",
    "Aujourd'hui, vous avez la chance de faire la différence dans la vie de quelqu'un. Saisissez-la ! 🌟",
    "Votre cœur est trop grand pour tenir en vous — c'est pourquoi il déborde vers vos patients. 💗",
    "Les soins infirmiers sont l'amour sous forme de profession. Et vous aimez avec excellence. 💯",
    "Dieu vous a préparée pour des moments comme celui-ci. Faites confiance à Son plan pour vous. 🗺️✝️",
    "Vous êtes la raison pour laquelle beaucoup de patients croient encore aux miracles. 🌈",
    "Merci de ne pas abandonner, même quand tout semble difficile. Vous êtes une guerrière ! ⚔️💪",
  ];

  const it = [
    "Sei le mani di Dio che si prendono cura di chi ne ha più bisogno. Il tuo lavoro trasforma vite. 🙏",
    "Ogni paziente che tocchi sente l'amore di Dio attraverso le tue mani. Continua a brillare! ✨",
    "L'infermieristica non è solo una professione, è una chiamata divina. Sei stata scelta per questo. 💙",
    "Il tuo sorriso può essere la migliore medicina che un paziente riceva oggi. Sorridi, fai la differenza! 😊",
    "Quando ti prendi cura di qualcuno, Dio si prende cura di te. Grazie per essere strumento di guarigione. 🌟",
    "L'infermieristica è l'arte di curare con scienza e amore. Tu padroneggi quest'arte! 💪",
    "Non tutti gli eroi indossano un mantello — alcuni indossano un camice e uno stetoscopio. Sei un'eroina! 🦸‍♀️",
    "Il tuo turno può essere lungo, ma il tuo impatto sulla vita delle persone è eterno. 🕊️",
    "Dio ha messo nelle tue mani il dono di guarire. Usalo con orgoglio e compassione. 💝",
    "Oggi è un altro giorno per salvare vite, alleviare il dolore e diffondere speranza. Ce la puoi fare! 🌈",
    "La tua dedizione ai tuoi pazienti ispira tutti intorno a te. 🌻",
    "Ogni atto di cura è una preghiera in azione. Sei una benedizione nella vita di molti. 🙌",
    "La tua forza non sta solo nella conoscenza tecnica, ma nell'amore che metti in ogni gesto. ❤️",
    "Il mondo ha bisogno di più persone come te — compassionevoli, dedicate e coraggiose. 🌍",
    "Quando la notte è lunga durante il turno, ricorda: sei la luce che guida i tuoi pazienti. 🌙",
    "Guarire è divino, prendersi cura è umano. Tu fai entrambe le cose con maestria. ⭐",
    "La tua presenza al capezzale vale più di qualsiasi medicina. Sei essenziale! 💎",
    "Dio ti ha dato mani che guariscono, occhi che vedono oltre la malattia e un cuore immenso. 💖",
    "Ogni giorno in ospedale è un'opportunità di essere la risposta alla preghiera di qualcuno. 🙏",
    "Trasformi la paura in conforto, il dolore in sollievo e la solitudine in calore. Grazie! 🤗",
    "L'infermieristica è la più grande prova che l'amore si manifesta attraverso l'azione. Sei amore in azione! 💕",
    "Anche nei giorni difficili, ricorda: sei insostituibile nella vita dei tuoi pazienti. 🏆",
    "Le tue mani portano la scienza e il tuo cuore porta la fede. Una combinazione perfetta! 🔬❤️",
    "Le cure che offri oggi piantano semi di gratitudine che fioriscono per sempre. 🌸",
    "Hai scelto una professione nobile. Il cielo sorride per ogni vita che tocchi. 😇",
    "Forza, dedizione e amore — i tre pilastri che ti rendono un'infermiera incredibile. 💫",
    "Ogni segno vitale che monitori è una vita che aiuti a proteggere. 📊",
    "Sei la prova vivente che servire gli altri è il più grande atto d'amore. 🕊️",
    "Nei momenti più difficili, la tua calma e competenza fanno tutta la differenza. 🧘‍♀️",
    "Grazie per essere il ponte tra la scienza e la cura umana. Sei straordinaria! 🌟",
    "Oggi, come ogni giorno, hai il potere di far sentire meglio qualcuno. Usa quel potere! ⚡",
    "Porti speranza nelle tue mani per chi giace in un letto d'ospedale. Questo è sacro. 🕊️",
    "Ogni goccia di sudore del tuo turno diventa lacrime di gratitudine dei pazienti. 💧",
    "Essere infermiera significa avere il coraggio di affrontare l'impossibile con un sorriso. 💪😊",
    "Sei l'angelo che Dio ha messo nei corridoi dell'ospedale. 👼",
    "La tua vocazione è un dono divino. Il mondo ti ringrazia per esistere. 🎁",
    "Quando tutto sembra difficile, ricorda perché hai iniziato. Sei nata per questo. 🌟",
    "L'amore che metti in ogni bendaggio va ben oltre la ferita. Guarisce l'anima. 💞",
    "Sei più forte di quanto immagini e più importante di quanto sai. 💎",
    "Ogni turno è una nuova possibilità di fare miracoli con le tue mani. ✨",
    "La notte può essere buia, ma la tua luce non si spegne mai. Brilla sempre! 🌙✨",
    "Curare è il verbo più bello che esista. E tu lo coniughi ogni giorno. 📖❤️",
    "Il tuo lavoro silenzioso salva vite. Non sottovalutare mai il tuo valore. 🏅",
    "Dio sceglie i cuori migliori per l'infermieristica. Tu ne sei la prova. 💝",
    "Ogni paziente che migliora è una tua vittoria. Festeggia ogni traguardo! 🎉",
    "Sei la personificazione della compassione. Il mondo ha disperatamente bisogno di te. 🌍💙",
    "La tua stanchezza di oggi è la guarigione di qualcuno domani. Ne vale la pena. 🙏",
    "La mano che cura è la stessa che conforta, accoglie e trasforma. La tua mano. 🤲",
    "Che la pace di Dio rinnovi le tue forze ad ogni nuovo turno. Te lo meriti. 🕊️",
    "Infermieristica: dove la scienza incontra il cuore. Tu sei quel bellissimo ponte. 🌉",
    "Ogni vita che tocchi porta il tuo segno d'amore per sempre. ♾️💕",
    "Non tratti solo malattie — ripristini la speranza. Questo è divino. ✝️",
    "Negli occhi di ogni paziente c'è gratitudine per la tua esistenza. Credici. 👁️💖",
    "La tua dedizione è una forma di preghiera. Dio ascolta ogni tuo gesto. 🙏✨",
    "Il camice che indossi porta il peso della responsabilità e la leggerezza dell'amore. ⚖️❤️",
    "Oggi hai la possibilità di fare la differenza nella vita di qualcuno. Coglila! 🌟",
    "Il tuo cuore è troppo grande per stare dentro di te — ecco perché trabocca verso i tuoi pazienti. 💗",
    "L'infermieristica è amore in forma di professione. E tu ami con eccellenza. 💯",
    "Dio ti ha preparata per momenti come questo. Fidati del Suo piano per te. 🗺️✝️",
    "Sei la ragione per cui molti pazienti credono ancora nei miracoli. 🌈",
    "Grazie per non arrenderti, anche quando tutto sembra difficile. Sei una guerriera! ⚔️💪",
  ];

  const ptpt = [
    "Você é a mão de Deus a cuidar de quem mais precisa. O seu trabalho transforma vidas. 🙏",
    "Cada paciente que toca sente o amor de Deus através das suas mãos. Continue a brilhar! ✨",
    "A enfermagem não é apenas uma profissão, é um chamamento divino. Foi escolhida para isto. 💙",
    "O seu sorriso pode ser o melhor remédio que um paciente recebe hoje. Sorria, faz a diferença! 😊",
    "Quando cuida de alguém, Deus cuida de si. Obrigada por ser instrumento de cura. 🌟",
    "A enfermagem é a arte de cuidar com ciência e amor. Domina essa arte! 💪",
    "Nem todos os heróis usam capa — alguns usam bata e estetoscópio. É uma heroína! 🦸‍♀️",
    "O seu turno pode ser longo, mas o seu impacto na vida das pessoas é eterno. 🕊️",
    "Deus colocou nas suas mãos o dom de curar. Use-o com orgulho e compaixão. 💝",
    "Hoje é mais um dia para salvar vidas, aliviar dores e espalhar esperança. Consegue! 🌈",
    "A sua dedicação aos seus pacientes inspira todos à sua volta. 🌻",
    "Cada ato de cuidado é uma oração em ação. É bênção na vida de muitos. 🙌",
    "A sua força não está apenas no conhecimento técnico, mas no amor que coloca em cada gesto. ❤️",
    "O mundo precisa de mais pessoas como si — compassivas, dedicadas e corajosas. 🌍",
    "Quando a noite é longa no turno, lembre-se: é a luz que guia os seus pacientes. 🌙",
    "Curar é divino, cuidar é humano. Faz as duas coisas com mestria. ⭐",
    "A sua presença junto ao leito vale mais do que qualquer medicamento. É essencial! 💎",
    "Deus deu-lhe mãos que curam, olhos que veem além da doença e um coração imenso. 💖",
    "Cada dia no hospital é uma oportunidade de ser a resposta à oração de alguém. 🙏",
    "Transforma medo em conforto, dor em alívio e solidão em acolhimento. Obrigada! 🤗",
    "A enfermagem é a maior prova de que o amor se manifesta em ações. É amor em ação! 💕",
    "Mesmo nos dias difíceis, lembre-se: é insubstituível na vida dos seus pacientes. 🏆",
    "As suas mãos carregam a ciência e o seu coração carrega a fé. Combinação perfeita! 🔬❤️",
    "O cuidado que oferece hoje planta sementes de gratidão que florescem para sempre. 🌸",
    "Escolheu uma profissão nobre. O céu sorri por cada vida que toca. 😇",
    "Força, dedicação e amor — os três pilares que fazem de si uma enfermeira incrível. 💫",
    "Cada sinal vital que monitoriza é uma vida que ajuda a proteger. 📊",
    "É prova viva de que servir o próximo é o maior ato de amor. 🕊️",
    "Nos momentos mais difíceis, a sua calma e competência fazem toda a diferença. 🧘‍♀️",
    "Obrigada por ser a ponte entre a ciência e o cuidado humano. É extraordinária! 🌟",
    "Hoje, como todos os dias, tem o poder de fazer alguém sentir-se melhor. Use esse poder! ⚡",
    "Carrega nas mãos a esperança de quem está num leito. Isso é sagrado. 🕊️",
    "Cada gota de suor do seu turno transforma-se em lágrimas de gratidão dos pacientes. 💧",
    "Ser enfermeira é ter coragem de enfrentar o impossível com um sorriso. 💪😊",
    "É o anjo que Deus colocou nos corredores do hospital. 👼",
    "A sua vocação é um presente divino. O mundo agradece por existir. 🎁",
    "Quando tudo parece difícil, lembre-se do porquê começou. Nasceu para isto. 🌟",
    "O amor que coloca em cada penso vai muito além da ferida. Cura a alma. 💞",
    "É mais forte do que imagina e mais importante do que sabe. 💎",
    "Cada turno é uma nova oportunidade de fazer milagres com as suas mãos. ✨",
    "A noite pode ser escura, mas a sua luz nunca se apaga. Brilhe sempre! 🌙✨",
    "Cuidar é o verbo mais bonito que existe. E conjuga-o todos os dias. 📖❤️",
    "O seu trabalho silencioso salva vidas. Nunca subestime o seu valor. 🏅",
    "Deus escolhe os melhores corações para a enfermagem. É prova disso. 💝",
    "Cada paciente que melhora é uma vitória sua. Celebre cada conquista! 🎉",
    "É a personificação da compaixão. O mundo precisa desesperadamente de si. 🌍💙",
    "O seu cansaço de hoje é a recuperação de alguém amanhã. Vale a pena. 🙏",
    "A mão que cuida é a mesma que conforta, acolhe e transforma. A sua mão. 🤲",
    "Que a paz de Deus renove as suas forças a cada novo turno. Merece. 🕊️",
    "Enfermagem: onde a ciência encontra o coração. É essa ponte linda. 🌉",
    "Cada vida que toca carrega a sua marca de amor para sempre. ♾️💕",
    "Não trata apenas doenças — restaura a esperança. Isso é divino. ✝️",
    "Nos olhos de cada paciente há gratidão pela sua existência. Acredite nisso. 👁️💖",
    "A sua dedicação é uma forma de oração. Deus ouve cada gesto seu. 🙏✨",
    "A bata que veste carrega o peso da responsabilidade e a leveza do amor. ⚖️❤️",
    "Hoje tem a oportunidade de ser a diferença na vida de alguém. Aproveite! 🌟",
    "O seu coração é grande demais para caber em si — por isso transborda para os seus pacientes. 💗",
    "A enfermagem é amor em forma de profissão. E ama com excelência. 💯",
    "Deus preparou-a para momentos como este. Confie no Seu plano para si. 🗺️✝️",
    "É a razão pela qual muitos pacientes ainda acreditam em milagres. 🌈",
    "Obrigada por não desistir, mesmo quando tudo parece difícil. É guerreira! ⚔️💪",
  ];

  // Nursing tips
  const tips: Record<string, string[]> = {
    'pt-BR': [
      "Lave as mãos antes e depois de cada procedimento — é a medida mais eficaz contra infecções.",
      "Sempre confira os 9 certos antes de administrar medicação: paciente, medicamento, dose, via, horário, registro, orientação, forma e resposta.",
      "Mantenha a cabeceira do leito elevada a 30-45° para pacientes com risco de broncoaspiração.",
      "Documente tudo: se não foi registrado, não foi feito.",
      "Hidrate-se durante o plantão — sua saúde importa tanto quanto a dos seus pacientes.",
      "Comunique-se de forma clara na passagem de plantão usando a técnica SBAR.",
      "Monitore sinais de flebite em acessos venosos periféricos a cada turno.",
      "Realize mudança de decúbito a cada 2 horas em pacientes acamados.",
      "Verifique alergias do paciente antes de qualquer administração medicamentosa.",
      "Mantenha o ambiente limpo e organizado — isso previne erros e infecções.",
      "Use luvas ao manipular fluidos corporais e descarte-as corretamente após o uso.",
      "Avalie a escala de dor do paciente regularmente e registre as intervenções.",
      "Identifique sinais precoces de sepse: febre, taquicardia, hipotensão e confusão mental.",
      "Mantenha o carrinho de emergência sempre verificado e pronto para uso.",
      "Priorize o conforto do paciente — posicionamento adequado reduz ansiedade e dor.",
      "Verifique a permeabilidade do acesso venoso antes de administrar medicações.",
      "Oriente o paciente sobre cada procedimento antes de realizá-lo — reduz ansiedade.",
      "Monitore o balanço hídrico em pacientes críticos ou com insuficiência renal/cardíaca.",
      "Use a escala de Braden para avaliar risco de lesão por pressão.",
      "Nunca recape agulhas — descarte diretamente no perfurocortante.",
      "Verifique a validade de todos os materiais antes de usar.",
      "Mantenha a privacidade do paciente durante procedimentos — feche cortinas e portas.",
      "Aqueça soluções intravenosas geladas antes de infundir — previne hipotermia.",
      "Observe sinais de sobrecarga hídrica: edema, dispneia, distensão jugular.",
      "Faça pausas durante o plantão para preservar sua saúde mental e física.",
      "Registre a evolução de enfermagem de forma objetiva, clara e completa.",
      "Use a técnica de aspiração correta para evitar trauma nas vias aéreas.",
      "Monitore glicemia capilar conforme prescrição e registre prontamente.",
      "Conheça os protocolos de emergência do seu setor — isso salva vidas.",
      "Pratique a escuta ativa com pacientes e familiares — humaniza o cuidado.",
    ],
    en: [
      "Wash your hands before and after every procedure — it's the most effective infection prevention measure.",
      "Always check the 9 rights before administering medication: patient, drug, dose, route, time, documentation, education, form, and response.",
      "Keep the head of bed elevated 30-45° for patients at risk of aspiration.",
      "Document everything: if it wasn't charted, it wasn't done.",
      "Stay hydrated during your shift — your health matters as much as your patients'.",
      "Communicate clearly during handoffs using the SBAR technique.",
      "Monitor for signs of phlebitis at peripheral IV sites every shift.",
      "Reposition bedridden patients every 2 hours to prevent pressure ulcers.",
      "Check patient allergies before any medication administration.",
      "Keep the environment clean and organized — it prevents errors and infections.",
      "Wear gloves when handling body fluids and dispose of them properly after use.",
      "Assess the patient's pain scale regularly and document interventions.",
      "Identify early signs of sepsis: fever, tachycardia, hypotension, and altered mental status.",
      "Keep the crash cart always checked and ready for use.",
      "Prioritize patient comfort — proper positioning reduces anxiety and pain.",
      "Verify IV patency before administering medications.",
      "Explain each procedure to the patient before performing it — reduces anxiety.",
      "Monitor fluid balance in critical patients or those with renal/cardiac insufficiency.",
      "Use the Braden Scale to assess pressure injury risk.",
      "Never recap needles — dispose directly into sharps containers.",
      "Check the expiration date of all materials before use.",
      "Maintain patient privacy during procedures — close curtains and doors.",
      "Warm cold IV solutions before infusing — prevents hypothermia.",
      "Watch for signs of fluid overload: edema, dyspnea, jugular distension.",
      "Take breaks during your shift to preserve your mental and physical health.",
      "Write nursing notes objectively, clearly, and completely.",
      "Use proper suctioning technique to avoid airway trauma.",
      "Monitor capillary blood glucose as prescribed and document promptly.",
      "Know your unit's emergency protocols — it saves lives.",
      "Practice active listening with patients and families — it humanizes care.",
    ],
    es: [
      "Lávese las manos antes y después de cada procedimiento — es la medida más eficaz contra infecciones.",
      "Siempre verifique los 9 correctos antes de administrar medicación.",
      "Mantenga la cabecera de la cama elevada 30-45° para pacientes con riesgo de broncoaspiración.",
      "Documente todo: si no se registró, no se hizo.",
      "Hidrátese durante el turno — su salud importa tanto como la de sus pacientes.",
      "Comuníquese claramente en el cambio de turno usando la técnica SBAR.",
      "Monitoree signos de flebitis en accesos venosos periféricos cada turno.",
      "Realice cambios posturales cada 2 horas en pacientes encamados.",
      "Verifique alergias del paciente antes de cualquier administración de medicamentos.",
      "Mantenga el ambiente limpio y organizado — esto previene errores e infecciones.",
      "Use guantes al manipular fluidos corporales y deséchelos correctamente.",
      "Evalúe la escala de dolor del paciente regularmente y registre las intervenciones.",
      "Identifique signos tempranos de sepsis: fiebre, taquicardia, hipotensión y confusión.",
      "Mantenga el carro de emergencia siempre verificado y listo para usar.",
      "Priorice el confort del paciente — el posicionamiento adecuado reduce ansiedad y dolor.",
      "Verifique la permeabilidad del acceso venoso antes de administrar medicaciones.",
      "Explique cada procedimiento al paciente antes de realizarlo — reduce la ansiedad.",
      "Monitoree el balance hídrico en pacientes críticos.",
      "Use la escala de Braden para evaluar riesgo de lesión por presión.",
      "Nunca reencapuche agujas — descarte directamente en el contenedor de cortopunzantes.",
      "Verifique la fecha de vencimiento de todos los materiales antes de usar.",
      "Mantenga la privacidad del paciente durante los procedimientos.",
      "Caliente soluciones intravenosas frías antes de infundir — previene hipotermia.",
      "Observe signos de sobrecarga hídrica: edema, disnea, distensión yugular.",
      "Tome pausas durante el turno para preservar su salud mental y física.",
      "Registre la evolución de enfermería de forma objetiva, clara y completa.",
      "Use la técnica de aspiración correcta para evitar trauma en las vías aéreas.",
      "Monitoree glucemia capilar según prescripción y registre prontamente.",
      "Conozca los protocolos de emergencia de su unidad — esto salva vidas.",
      "Practique la escucha activa con pacientes y familiares — humaniza el cuidado.",
    ],
    fr: [
      "Lavez-vous les mains avant et après chaque procédure — c'est la mesure la plus efficace contre les infections.",
      "Vérifiez toujours les 9 règles avant d'administrer un médicament.",
      "Maintenez la tête du lit surélevée à 30-45° pour les patients à risque d'aspiration.",
      "Documentez tout : si ce n'est pas noté, ce n'est pas fait.",
      "Restez hydraté(e) pendant votre garde — votre santé compte autant que celle de vos patients.",
      "Communiquez clairement lors des transmissions en utilisant la technique SBAR.",
      "Surveillez les signes de phlébite sur les accès veineux périphériques à chaque poste.",
      "Repositionnez les patients alités toutes les 2 heures pour prévenir les escarres.",
      "Vérifiez les allergies du patient avant toute administration médicamenteuse.",
      "Maintenez l'environnement propre et organisé — cela prévient les erreurs et les infections.",
      "Portez des gants lors de la manipulation de fluides corporels et éliminez-les correctement.",
      "Évaluez régulièrement l'échelle de douleur du patient et documentez les interventions.",
      "Identifiez les signes précoces de sepsis : fièvre, tachycardie, hypotension et confusion.",
      "Gardez le chariot d'urgence toujours vérifié et prêt à l'emploi.",
      "Priorisez le confort du patient — un positionnement correct réduit l'anxiété et la douleur.",
      "Vérifiez la perméabilité de la voie veineuse avant d'administrer des médicaments.",
      "Expliquez chaque procédure au patient avant de la réaliser — réduit l'anxiété.",
      "Surveillez le bilan hydrique chez les patients critiques.",
      "Utilisez l'échelle de Braden pour évaluer le risque d'escarre.",
      "Ne recapuchonnez jamais les aiguilles — jetez-les directement dans le conteneur.",
      "Vérifiez la date de péremption de tout le matériel avant utilisation.",
      "Maintenez l'intimité du patient pendant les procédures — fermez rideaux et portes.",
      "Réchauffez les solutions intraveineuses froides avant de les perfuser.",
      "Surveillez les signes de surcharge hydrique : œdème, dyspnée, distension jugulaire.",
      "Faites des pauses pendant votre garde pour préserver votre santé mentale et physique.",
      "Rédigez les notes infirmières de manière objective, claire et complète.",
      "Utilisez la technique d'aspiration correcte pour éviter les traumatismes des voies aériennes.",
      "Surveillez la glycémie capillaire selon la prescription et documentez rapidement.",
      "Connaissez les protocoles d'urgence de votre service — cela sauve des vies.",
      "Pratiquez l'écoute active avec les patients et les familles — cela humanise les soins.",
    ],
    it: [
      "Lavati le mani prima e dopo ogni procedura — è la misura più efficace contro le infezioni.",
      "Verifica sempre le 9 regole prima di somministrare farmaci.",
      "Mantieni la testata del letto sollevata a 30-45° per i pazienti a rischio di aspirazione.",
      "Documenta tutto: se non è stato registrato, non è stato fatto.",
      "Resta idratato/a durante il turno — la tua salute conta quanto quella dei tuoi pazienti.",
      "Comunica chiaramente durante il passaggio di consegne usando la tecnica SBAR.",
      "Monitora i segni di flebite negli accessi venosi periferici ad ogni turno.",
      "Cambia posizione ai pazienti allettati ogni 2 ore per prevenire le lesioni da pressione.",
      "Verifica le allergie del paziente prima di qualsiasi somministrazione di farmaci.",
      "Mantieni l'ambiente pulito e organizzato — previene errori e infezioni.",
      "Indossa i guanti quando maneggi fluidi corporei e smaltiscili correttamente.",
      "Valuta regolarmente la scala del dolore del paziente e documenta gli interventi.",
      "Identifica i segni precoci di sepsi: febbre, tachicardia, ipotensione e confusione.",
      "Mantieni il carrello delle emergenze sempre controllato e pronto all'uso.",
      "Dai priorità al comfort del paziente — un posizionamento corretto riduce ansia e dolore.",
      "Verifica la pervietà dell'accesso venoso prima di somministrare farmaci.",
      "Spiega ogni procedura al paziente prima di eseguirla — riduce l'ansia.",
      "Monitora il bilancio idrico nei pazienti critici.",
      "Usa la scala di Braden per valutare il rischio di lesioni da pressione.",
      "Non reincappucciare mai gli aghi — smaltiscili direttamente nel contenitore.",
      "Controlla la data di scadenza di tutti i materiali prima dell'uso.",
      "Mantieni la privacy del paziente durante le procedure — chiudi tende e porte.",
      "Riscalda le soluzioni endovenose fredde prima di infonderle — previene l'ipotermia.",
      "Osserva i segni di sovraccarico idrico: edema, dispnea, distensione giugulare.",
      "Fai delle pause durante il turno per preservare la tua salute mentale e fisica.",
      "Scrivi le note infermieristiche in modo obiettivo, chiaro e completo.",
      "Usa la tecnica di aspirazione corretta per evitare traumi delle vie aeree.",
      "Monitora la glicemia capillare secondo prescrizione e documenta prontamente.",
      "Conosci i protocolli di emergenza del tuo reparto — salva vite.",
      "Pratica l'ascolto attivo con pazienti e familiari — umanizza le cure.",
    ],
    'pt-PT': [
      "Lave as mãos antes e depois de cada procedimento — é a medida mais eficaz contra infeções.",
      "Verifique sempre os 9 certos antes de administrar medicação.",
      "Mantenha a cabeceira da cama elevada a 30-45° para pacientes com risco de broncoaspiração.",
      "Documente tudo: se não foi registado, não foi feito.",
      "Hidrate-se durante o turno — a sua saúde importa tanto como a dos seus pacientes.",
      "Comunique de forma clara na passagem de turno utilizando a técnica SBAR.",
      "Monitorize sinais de flebite em acessos venosos periféricos a cada turno.",
      "Realize mudança de decúbito a cada 2 horas em pacientes acamados.",
      "Verifique alergias do paciente antes de qualquer administração medicamentosa.",
      "Mantenha o ambiente limpo e organizado — isso previne erros e infeções.",
      "Use luvas ao manipular fluidos corporais e descarte-as corretamente.",
      "Avalie a escala de dor do paciente regularmente e registe as intervenções.",
      "Identifique sinais precoces de sepsis: febre, taquicardia, hipotensão e confusão mental.",
      "Mantenha o carro de emergência sempre verificado e pronto para uso.",
      "Priorize o conforto do paciente — posicionamento adequado reduz ansiedade e dor.",
      "Verifique a permeabilidade do acesso venoso antes de administrar medicações.",
      "Oriente o paciente sobre cada procedimento antes de o realizar — reduz ansiedade.",
      "Monitorize o balanço hídrico em pacientes críticos.",
      "Use a escala de Braden para avaliar risco de lesão por pressão.",
      "Nunca reencapsule agulhas — descarte diretamente no contentor de cortantes.",
      "Verifique a validade de todos os materiais antes de usar.",
      "Mantenha a privacidade do paciente durante procedimentos — feche cortinas e portas.",
      "Aqueça soluções intravenosas frias antes de infundir — previne hipotermia.",
      "Observe sinais de sobrecarga hídrica: edema, dispneia, distensão jugular.",
      "Faça pausas durante o turno para preservar a sua saúde mental e física.",
      "Registe a evolução de enfermagem de forma objetiva, clara e completa.",
      "Use a técnica de aspiração correta para evitar trauma nas vias aéreas.",
      "Monitorize glicemia capilar conforme prescrição e registe prontamente.",
      "Conheça os protocolos de emergência do seu serviço — isso salva vidas.",
      "Pratique a escuta ativa com pacientes e familiares — humaniza o cuidado.",
    ],
  };

  const allQuotes: Record<string, string[]> = {
    'pt-BR': ptbr, en, es, fr, it, 'pt-PT': ptpt,
  };

  let totalQuotes = 0;
  let totalTips = 0;

  // Insert quotes
  for (const [lang, quotes] of Object.entries(allQuotes)) {
    const rows = quotes.map((q, i) => ({ language: lang, sort_order: i + 1, quote: q }));
    const { error } = await supabase.from("motivational_quotes").insert(rows);
    if (error) {
      return new Response(JSON.stringify({ error: `Quotes ${lang}: ${error.message}` }), {
        status: 500,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }
    totalQuotes += rows.length;
  }

  // Insert tips
  for (const [lang, tipList] of Object.entries(tips)) {
    const rows = tipList.map((t, i) => ({ language: lang, sort_order: i + 1, tip: t }));
    const { error } = await supabase.from("nursing_tips").insert(rows);
    if (error) {
      return new Response(JSON.stringify({ error: `Tips ${lang}: ${error.message}` }), {
        status: 500,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }
    totalTips += rows.length;
  }

  return new Response(
    JSON.stringify({ success: true, totalQuotes, totalTips }),
    { headers: { ...corsHeaders, "Content-Type": "application/json" } }
  );
});
