// This file is automatically generated. Do not edit it directly.
import { Capacitor } from '@capacitor/core';
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://igylprpvqunjpfsagnkr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlneWxwcnB2cXVuanBmc2FnbmtyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU1MjQ5ODIsImV4cCI6MjA5MTEwMDk4Mn0.URRJoKPHan_-JDP8Kfo1KSy8ooZIS2IT1w84hPDnFgk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: !Capacitor.isNativePlatform(),
    flowType: 'pkce',
  }
});